<?php
/**
 * @var $block \Magentando\OrderHistoryLine\Block\Adminhtml\StatusLine
 */
?>
<?= $block->displayLine() ?>
<style>
    .order-historyline ul li{
        display: inline-block;
        padding: 15px;
        background: #0fa7ff;

    }
    .order-historyline ul li:after{
        margin-left: 15px;
    }
</style>
<div class="order-historyline">
    <ul>
        <li>acao 1</li>
        <li>acao 2</li>
        <li>acao 3</li>
        <li>acao 4</li>
        <li>acao 5</li>
    </ul>
</div>
